class Province {
  final String name;
  final String address;
  final String image;
  final double latitude;
  final double longitude;

  Province({
    required this.name,
    required this.address,
    required this.image,
    required this.latitude,
    required this.longitude,
  });
}

final List<Province> provinces = [
  Province(
    name: 'Riau',
    address: 'Alamat Kantor Gubernur Riau',
    image: 'assets/province_images/riau.png',
    latitude: 0.5071,
    longitude: 101.4478,
  ),
  Province(
    name: 'Kepulauan Riau',
    address: 'Alamat Kantor Gubernur Kepulauan Riau',
    image: 'assets/province_images/kepulauan_riau.png',
    latitude: 0.9227,
    longitude: 104.4676,
  ),
  Province(
    name: 'Jambi',
    address: 'Alamat Kantor Gubernur Jambi',
    image: 'assets/province_images/jambi.png',
    latitude: -1.4854,
    longitude: 102.4381,
  ),
  Province(
    name: 'Bengkulu',
    address: 'Alamat Kantor Gubernur Bengkulu',
    image: 'assets/province_images/bengkulu.png',
    latitude: -3.5778,
    longitude: 102.3464,
  ),
  Province(
    name: 'Sumatera Selatan',
    address: 'Alamat Kantor Gubernur Sumatera Selatan',
    image: 'assets/province_images/sumatera_selatan.png',
    latitude: -3.3191,
    longitude: 104.9140,
  ),
  Province(
    name: 'Bangka Belitung',
    address: 'Alamat Kantor Gubernur Bangka Belitung',
    image: 'assets/province_images/bangka_belitung.png',
    latitude: -2.7411,
    longitude: 106.4405,
  ),
  Province(
    name: 'Lampung',
    address: 'Alamat Kantor Gubernur Lampung',
    image: 'assets/province_images/lampung.png',
    latitude: -4.5586,
    longitude: 105.4068,
  ),
  Province(
    name: 'Banten',
    address: 'Alamat Kantor Gubernur Banten',
    image: 'assets/province_images/banten.png',
    latitude: -6.4058,
    longitude: 106.0640,
  ),
  Province(
    name: 'DKI Jakarta',
    address: 'Alamat Kantor Gubernur DKI Jakarta',
    image: 'assets/province_images/dki_jakarta.png',
    latitude: -6.2088,
    longitude: 106.8456,
  ),
  Province(
    name: 'Jawa Barat',
    address: 'Alamat Kantor Gubernur Jawa Barat',
    image: 'assets/province_images/jawa_barat.png',
    latitude: -6.9244,
    longitude: 107.6077,
  ),
  Province(
    name: 'Jawa Tengah',
    address: 'Alamat Kantor Gubernur Jawa Tengah',
    image: 'assets/province_images/jawa_tengah.png',
    latitude: -7.1500,
    longitude: 110.1403,
  ),
  Province(
    name: 'DI Yogyakarta',
    address: 'Alamat Kantor Gubernur DI Yogyakarta',
    image: 'assets/province_images/di_yogyakarta.png',
    latitude: -7.8012,
    longitude: 110.3649,
  ),
  Province(
    name: 'Jawa Timur',
    address: 'Alamat Kantor Gubernur Jawa Timur',
    image: 'assets/province_images/jawa_timur.png',
    latitude: -7.5361,
    longitude: 112.2384,
  ),
  Province(
    name: 'Bali',
    address: 'Alamat Kantor Gubernur Bali',
    image: 'assets/province_images/bali.png',
    latitude: -8.3405,
    longitude: 115.0919,
  ),
  Province(
    name: 'Nusa Tenggara Barat',
    address: 'Alamat Kantor Gubernur Nusa Tenggara Barat',
    image: 'assets/province_images/nusa_tenggara_barat.png',
    latitude: -8.6529,
    longitude: 116.3996,
  ),
  Province(
    name: 'Nusa Tenggara Timur',
    address: 'Alamat Kantor Gubernur Nusa Tenggara Timur',
    image: 'assets/province_images/nusa_tenggara_timur.png',
    latitude: -8.6574,
    longitude: 121.0794,
  ),
  Province(
    name: 'Kalimantan Barat',
    address: 'Alamat Kantor Gubernur Kalimantan Barat',
    image: 'assets/province_images/kalimantan_barat.png',
    latitude: -0.0236,
    longitude: 109.3425,
  ),
  Province(
    name: 'Kalimantan Tengah',
    address: 'Alamat Kantor Gubernur Kalimantan Tengah',
    image: 'assets/province_images/kalimantan_tengah.png',
    latitude: -2.1833,
    longitude: 113.4690,
  ),
  Province(
    name: 'Kalimantan Selatan',
    address: 'Alamat Kantor Gubernur Kalimantan Selatan',
    image: 'assets/province_images/kalimantan_selatan.png',
    latitude: -3.3167,
    longitude: 114.5921,
  ),
  Province(
    name: 'Kalimantan Timur',
    address: 'Alamat Kantor Gubernur Kalimantan Timur',
    image: 'assets/province_images/kalimantan_timur.png',
    latitude: 0.3476,
    longitude: 117.3962,
  ),
  Province(
    name: 'Kalimantan Utara',
    address: 'Alamat Kantor Gubernur Kalimantan Utara',
    image: 'assets/province_images/kalimantan_utara.png',
    latitude: 3.3266,
    longitude: 117.5433,
  ),
  Province(
    name: 'Gorontalo',
    address: 'Alamat Kantor Gubernur Gorontalo',
    image: 'assets/province_images/gorontalo.png',
    latitude: 0.6999,
    longitude: 122.4467,
  ),
  Province(
    name: 'Sulawesi Utara',
    address: 'Alamat Kantor Gubernur Sulawesi Utara',
    image: 'assets/province_images/sulawesi_utara.png',
    latitude: 0.6247,
    longitude: 123.9750,
  ),
  Province(
    name: 'Sulawesi Tengah',
    address: 'Alamat Kantor Gubernur Sulawesi Tengah',
    image: 'assets/province_images/sulawesi_tengah.png',
    latitude: -1.4300,
    longitude: 121.4456,
  ),
  Province(
    name: 'Sulawesi Barat',
    address: 'Alamat Kantor Gubernur Sulawesi Barat',
    image: 'assets/province_images/sulawesi_barat.png',
    latitude: -2.8361,
    longitude: 119.2321,
  ),
  Province(
    name: 'Sulawesi Selatan',
    address: 'Alamat Kantor Gubernur Sulawesi Selatan',
    image: 'assets/province_images/sulawesi_selatan.png',
    latitude: -4.7608,
    longitude: 119.5383,
  ),
  Province(
    name: 'Maluku',
    address: 'Alamat Kantor Gubernur Maluku',
    image: 'assets/province_images/maluku.png',
    latitude: -3.2385,
    longitude: 130.1452,
  ),
  Province(
    name: 'Maluku Utara',
    address: 'Alamat Kantor Gubernur Maluku Utara',
    image: 'assets/province_images/maluku_utara.png',
    latitude: 1.5698,
    longitude: 127.8089,
  ),
  Province(
    name: 'Papua Barat',
    address: 'Alamat Kantor Gubernur Papua Barat',
    image: 'assets/province_images/papua_barat.png',
    latitude: -1.3870,
    longitude: 132.4376,
  ),
  Province(
    name: 'Papua',
    address: 'Alamat Kantor Gubernur Papua',
    image: 'assets/province_images/papua.png',
    latitude: -4.2699,
    longitude: 138.0804,
  ),
];
